### PR TITLE
Added ADRIXSCam to main areaDetector main repo

### PR DESCRIPTION
**Pull request by stuwilkins**

### CODE REVIEW

**Comment by stuwilkins** [comment]
@MarkRivers Could you please have a look at this? This is to add the ADRIXSCam from XCAM. They have pushed to areaDetector/ADRIXSCam.

**Comment by stuwilkins** [comment]
Note this should not be merged until the ADRIXSCam PR is merged or the docs will break.

**Comment by MarkRivers** [comment]
This looks OK to me.  Let me know when you want to merge.

**Comment by stuwilkins** [comment]
Hi @MarkRivers, this should go along with https://github.com/areaDetector/ADRIXSCam/pull/2 which is the rebuilt driver, could you please have a look at that. As far as I am concerned both can be merged!

**Pull request merged**
