### PR TITLE
Added specAnalyser repo

### PR DESCRIPTION
**Pull request by stuwilkins**
HI! This PR is adding the new specsAnalyser repo to the main areaDetector repo. Please don't merge until the specsAnalyser repo builds OK on this infrastructure. Thanks @ulrikpedersen and @MarkRivers

### CODE REVIEW

**Comment by stuwilkins** [comment]
@MarkRivers if travis builds the docs ok can we merge this..... we would like to get the specsAnalyser into the main repo. Thanks!

**Comment by stuwilkins** [comment]
Note: this needs this PR:

https://github.com/areaDetector/specsAnalyser/pull/1

**Comment by stuwilkins** [comment]
@MarkRivers Ok to merge this and https://github.com/areaDetector/specsAnalyser/pull/1 ??

**Comment by MarkRivers** [comment]
I’m going be at the ALS review (with you!) so I’ll look at this next week.

**Comment by stuwilkins** [comment]
Ok thanks ... I won’t be at the review because I can’t fly after my knee surgery but will be there remotely. Next week is fine! Thanks!

**Comment by MarkRivers** [comment]
I managed to do this on my phone. Seems liked it worked.

**Pull request merged**
