### PR TITLE
Adding ADTimePix3 submodule

### PR DESCRIPTION
**Pull request by kgofron**
I am adding a submodule to the TimePix3 detector. Please let me know if I missed something.
The .opi screens are included with the driver.

### CODE REVIEW

**Comment by jwlodek** [comment]
Should the docs be updated with links to pages for the timepix?

**Comment by kgofron** [comment]
Updated some of the docs. Not sure how to test.

**Comment by MarkRivers** [comment]
I added the link to ADTimePix3 in docs/source/detector_drivers.rst.

The ADTimePix3 documentation is now visible in areaDetector.github.io:
https://areadetector.github.io/areaDetector/ADTimePix3/ADTimePix3.html

**Comment by kgofron** [comment]
Thank you Mark. 
ADTimePix3 needs a section in docs/source/detectors.rst.
Do you want me to create a pull request for this?

**Comment by antoninomiceli** [comment]
Just curious, which vendor is the Timepix3 from? Aren't there multiple vendors?

**Comment by MarkRivers** [comment]
The README.md says:

An EPICS areaDetector driver for TimePix3 detector from [ASC](https://www.amscins.com/).

**Comment by MarkRivers** [comment]
> ADTimePix3 needs a section in docs/source/detectors.rst.

There are lots of recent detectors without entries there (ADSpinnaker, ADVimba, ADEuresys, etc.) I am thinking of deleting that file, since it largely duplicates information in detector_drivers.rst and it is work to maintain it.

**Pull request merged**
