### PR TITLE
Move docs to sphinx / github pages

### PR DESCRIPTION
**Pull request by stuwilkins**
After discussion with @MarkRivers I am going to have a go at converting the AD docs over to sphinx. I have a test I did on the ADFastCCD repo for the driver I authored. That can be seen here:

https://adfastccd.readthedocs.io/en/latest/

After talking to some more docs experts at @NSLS-II (thanks @danielballan !!) they suggested using drdoctr/doctr so that the docs can be pushed up to github pages. 

My suggestion it to:

* Run travis on areaDetector to deploy to github pages
* Create a docs dir which contains the master docs and the build infrastructure for sphinx
* Each repo creates a `ADXXX/docs` directory with the docs

This PR is just WIP at the moment ...

### CODE REVIEW

**Comment by stuwilkins** [comment]
To get this working on travis, can someone enable travis on `areaDetector/areaDetector`. Also we need a repo `areaDetector.github.io` in the `areaDetector` org if docs go there.

**Comment by MarkRivers** [comment]
> Also we need a repo areaDetector.github.io in the areaDetector org if docs go there.

I have created that.

**Comment by MarkRivers** [comment]
> To get this working on travis, can someone enable travis on areaDetector/areaDetector.

I don't think I have ever created a new Travis CI project, I've just edited existing ones.  When I click on the Travis CI via the "Continuous integration" link on this page it seems to want me to pay!  How do we do this for free?

**Comment by MarkRivers** [comment]
I think I added this repository to Travis.  Can you create the travis.yml file and test?

**Comment by MarkRivers** [comment]
I merged and pulled to my host.  When I run make in the docs/ directory I get this:
```
corvette:~/devel/areaDetector/docs>make
Sphinx v1.1.3
Usage: /bin/sphinx-build [options] sourcedir outdir [filenames...]
Options: -b <builder> -- builder to use; default is html
         -a        -- write all files; default is to only write new and changed files
         -E        -- don't use a saved environment, always read all files
         -t <tag>  -- include "only" blocks with <tag>
         -d <path> -- path for the cached environment and doctree files
                      (default: outdir/.doctrees)
         -c <path> -- path where configuration file (conf.py) is located
                      (default: same as sourcedir)
         -C        -- use no config file at all, only -D options
         -D <setting=value> -- override a setting in configuration
         -A <name=value>    -- pass a value into the templates, for HTML builder
         -n        -- nit-picky mode, warn about all missing references
         -N        -- do not do colored output
         -q        -- no output on stdout, just warnings on stderr
         -Q        -- no output at all, not even warnings
         -w <file> -- write warnings (and errors) to given file
         -W        -- turn warnings into errors
         -P        -- run Pdb on exception
Modi:
* without -a and without filenames, write new and changed files.
* with -a, write all files.
* with filenames, write these.
make: *** [help] Error 1
```

Am I doing something wrong?

**Comment by MarkRivers** [comment]
With the new Makefile things are worse:
```
corvette:~/devel/areaDetector/docs>make
sphinx-multibuild  -i source -s _docs  -o ./_build/html -b html
make: sphinx-multibuild: Command not found
make: *** [all] Error 127

corvette:~/devel/areaDetector/docs>make html
make: *** No rule to make target `html'.  Stop.
```

This version of sphinx is the one that ships with Centos7, and probably also RHEL7.  There is no yum update available for a more recent version.  I think it would be good to make the docs work with that version of sphinx.

These are the sphinx commands available in that version:
```
corvette:~/devel/areaDetector/docs>sphinx-
sphinx-apidoc     sphinx-autogen    sphinx-build      sphinx-quickstart
```

**Comment by MarkRivers** [comment]
I tried to install sphinx using pip as documented on the sphinx github page.  That led to the following:
```
corvette:~/devel/areaDetector/docs>sudo pip install -U sphinx
[sudo] password for epics:
Collecting sphinx
  Downloading https://files.pythonhosted.org/packages/0e/5c/e7d076cf2900b38cba5c7d48545953540d86634d391b702067c00d99cb01/Sphinx-1.8.3-py2.py3-none-any.whl (3.1MB)
    100% |################################| 3.1MB 5.8MB/s
Collecting snowballstemmer>=1.1 (from sphinx)
  Downloading https://files.pythonhosted.org/packages/d4/6c/8a935e2c7b54a37714656d753e4187ee0631988184ed50c0cf6476858566/snowballstemmer-1.2.1-py2.py3-none-any.whl (64kB)
    100% |################################| 71kB 29.3MB/s
Collecting alabaster<0.8,>=0.7 (from sphinx)
  Downloading https://files.pythonhosted.org/packages/10/ad/00b090d23a222943eb0eda509720a404f531a439e803f6538f35136cae9e/alabaster-0.7.12-py2.py3-none-any.whl
Collecting sphinxcontrib-websupport (from sphinx)
  Downloading https://files.pythonhosted.org/packages/52/69/3c2fbdc3702358c5b34ee25e387b24838597ef099761fc9a42c166796e8f/sphinxcontrib_websupport-1.1.0-py2.py3-none-any.whl
Collecting Pygments>=2.0 (from sphinx)
  Downloading https://files.pythonhosted.org/packages/13/e5/6d710c9cf96c31ac82657bcfb441df328b22df8564d58d0c4cd62612674c/Pygments-2.3.1-py2.py3-none-any.whl (849kB)
    100% |################################| 849kB 16.5MB/s
Collecting requests>=2.0.0 (from sphinx)
  Downloading https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl (57kB)
    100% |################################| 61kB 13.6MB/s
Requirement already satisfied, skipping upgrade: setuptools in /usr/lib/python2.7/site-packages (from sphinx) (0.9.8)
Collecting babel!=2.0,>=1.3 (from sphinx)
  Downloading https://files.pythonhosted.org/packages/b8/ad/c6f60602d3ee3d92fbed87675b6fb6a6f9a38c223343ababdb44ba201f10/Babel-2.6.0-py2.py3-none-any.whl (8.1MB)
    100% |################################| 8.1MB 4.2MB/s
Requirement already satisfied, skipping upgrade: docutils>=0.11 in /usr/lib/python2.7/site-packages (from sphinx) (0.11)
Collecting packaging (from sphinx)
  Downloading https://files.pythonhosted.org/packages/89/d1/92e6df2e503a69df9faab187c684585f0136662c12bb1f36901d426f3fab/packaging-18.0-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: Jinja2>=2.3 in /usr/lib/python2.7/site-packages (from sphinx) (2.8)
Collecting typing; python_version < "3.5" (from sphinx)
  Downloading https://files.pythonhosted.org/packages/cc/3e/29f92b7aeda5b078c86d14f550bf85cff809042e3429ace7af6193c3bc9f/typing-3.6.6-py2-none-any.whl
Collecting imagesize (from sphinx)
  Downloading https://files.pythonhosted.org/packages/fc/b6/aef66b4c52a6ad6ac18cf6ebc5731ed06d8c9ae4d3b2d9951f261150be67/imagesize-1.1.0-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: six>=1.5 in /usr/lib/python2.7/site-packages (from sphinx) (1.11.0)
Collecting urllib3<1.25,>=1.21.1 (from requests>=2.0.0->sphinx)
  Downloading https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl (118kB)
    100% |################################| 122kB 18.8MB/s
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.0.0->sphinx)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |################################| 143kB 33.1MB/s
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /usr/lib/python2.7/site-packages (from requests>=2.0.0->sphinx) (2.7)
Collecting certifi>=2017.4.17 (from requests>=2.0.0->sphinx)
  Downloading https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl (154kB)
    100% |################################| 163kB 37.7MB/s
Collecting pytz>=0a (from babel!=2.0,>=1.3->sphinx)
  Downloading https://files.pythonhosted.org/packages/61/28/1d3920e4d1d50b19bc5d24398a7cd85cc7b9a75a490570d5a30c57622d34/pytz-2018.9-py2.py3-none-any.whl (510kB)
    100% |################################| 512kB 30.2MB/s
Collecting pyparsing>=2.0.2 (from packaging->sphinx)
  Downloading https://files.pythonhosted.org/packages/71/e8/6777f6624681c8b9701a8a0a5654f3eb56919a01a78e12bf3c73f5a3c714/pyparsing-2.3.0-py2.py3-none-any.whl (59kB)
    100% |################################| 61kB 27.8MB/s
Requirement already satisfied, skipping upgrade: MarkupSafe in /usr/lib64/python2.7/site-packages (from Jinja2>=2.3->sphinx) (0.11)
Installing collected packages: snowballstemmer, alabaster, sphinxcontrib-websupport, Pygments, urllib3, chardet, certifi, requests, pytz, babel, pyparsing, packaging, typing, imagesize, sphinx
  Found existing installation: Pygments 1.4
    Uninstalling Pygments-1.4:
      Successfully uninstalled Pygments-1.4
  Found existing installation: Babel 0.9.6
    Uninstalling Babel-0.9.6:
      Successfully uninstalled Babel-0.9.6
  Found existing installation: pyparsing 1.5.6
Cannot uninstall 'pyparsing'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
corvette:~/devel/areaDetector/docs>
```
So it failed after uninstalling some packages, which is not nice.

Suggestions?

**Comment by stuwilkins** [comment]
This is always the issue with anything in python. I think there are a couple of ways round this, the first is to use something like conda (which is what I do on my Mac) to separate from system python. That has the advantage that you don’t need root access to get new packages. I know it is a pain, but we have faced the same here that all the system python installs are really out of date (we are still on Debian 8 here in places) 

I would suggest using conda:

Have a look at:

https://conda.io/docs/user-guide/install/index.html <https://conda.io/docs/user-guide/install/index.html>

There is a cheat sheet at:

https://conda.io/docs/user-guide/install/index.html <https://conda.io/docs/user-guide/install/index.html>

You can then do:

pip install -r requirements.txt

From the root of the areaDetector/areaDetector 

This is now the “go to” for most of the data analysis stuff at NSLS-II……

**Comment by prjemian** [comment]
I, too, recommend this approach.  At APS, we provide conda-installed 
sphinx for Python 2.7 and Python 3.6 on the /APSshare file share, 
available on each sector's DSERV.  We maintain this installation so we 
don't have to adjust the system-provided python.

**Pull request merged**
