### PR TITLE
Eliminated the need to modify the top-level AD Makefile.

### LINKED ISSUE #9: Editing Makefile is required for build to succeed
The only exception is if the user obtained areaDetector by doing a "git clone --recursive".  The Makefile should be modified so that the drivers to be built are specified in a RELEASE file.  All drivers should be commented out by default.  Users should only have to uncomment the lines corresponding to the drivers they want to build.

### PR DESCRIPTION
**Pull request by kmpeters**
The top-level Makefile has been modified so that drivers to be built can be specified in RELEASE.local, which eliminates the need for users to modify the Makefile.  None of the drivers are built by default, so building the areaDetector tar file should succeed after only modifying files in the configure directory.

Fixes #9

### CODE REVIEW

**Comment by MarkRivers** [comment]
I think there may be a problem with this.  Doesn't it introduce "cross-talk" between detector driver modules when building from the top level?  For example, if I uncomment ADPROSILICA and ADANDOR in RELEASE.local and run make from the top-level, then when it builds ADProsilica won't make also include ADAndor/include and ADAndor/lib/$(ARCH) in the list of directories it searches when it looks for include files and libraries?  That can be bad: what if the Prosilica and Andor vendor libraries both provide an include file called Camera.h or a library called libCamera.so?  In the current system that is not a problem when building from the top-level, because when it builds ADProsilica the path to ADAndor is never defined in a RELEASE file.  But with this change I think it would search the ADAndor directory when building ADProsilica. 

I can't really test this, because I would have to accept your commit to the master branch on github to test it.  Can you please change your pull request from being on the master branch to being on a new branch for testing?  Also, can you please try uncommenting several detectors in your RELEASE.local and then send the complete output of "make" when building one of the detectors?

I also don't like the fact that ADBinaries is now only built on Windows.  While ADBinaries currently only has files for Window, this could change in the future, and I don't think we should limit ourselves with the Makefile.  It is quick and harmless to build ADBinaries on all architectures.

**Comment by MarkRivers** [comment]
My previous comment was incorrect.  I was able to test by cloning kmpeters:areaDetector and copying Makefile to my working directory areaDetector/Makefile and copying configure/EXAMPLE_RELEASE.local to configure/RELEASE.local.  I uncommented ADANDOR, ADANDOR3 and ADPROSILICA from RELEASE.local.  When I built from the top-level I found that there was no cross-talk between modules, e.g. ADAndor was not searched when building ADProsilica, etc.
I am accepting the pull request, but I will modifiy the Makefile to using ADBinaries on all architectures and push that back.

**Comment by kmpeters** [comment]
> I also don't like the fact that ADBinaries is now only built on Windows. While ADBinaries currently only has files for Window, this could change in the future, and I don't think we should limit ourselves with the Makefile. It is quick and harmless to build ADBinaries on all architectures.

It seems strange to require users who are not building areaDetector on Windows to download and install a package that only contains Windows libraries.  It would be easy to update the Makefile if ADBinaries includes non-Windows libraries in the future.

If ADBinaries continues to be a requirement to build for all platforms, the ADBinaries README.md should be modified to reflect this.

**Comment by MarkRivers** [comment]
I can see your point.  areaDetector/configure/EXAMPLE_RELEASE_LIBS.local contains this line:
ADBINARIES=$(AREA_DETECTOR)/ADBinaries

So ADBINARIES is defined on all platforms, and the EPICS will look for it on all ARCHs.  It appears to be harmless if it does not exist however.

**Pull request merged**
